### ISSUE TITLE
Info #Updates #Bugs #Info

### ISSUE THREAD

**Issue by HyGlobalHD** [BackToAction/ARCore#1]
- Knockback Booster AKA Redstone RocketPads Doesnt Work
- Some Files Are Not Working.

**Comment by HyGlobalHD** [comment]
- Fixed RocketPads
- File Not Working

**Comment by HyGlobalHD** [comment]
- Fixed RocketPads

**Comment by HyGlobalHD** [comment]
Trying To Implement Songs But With Bugs.
The Song Features Will Be Delay After The Bugs Fixs.

**Comment by jdot-r** [comment]
I have a request, could I join your organization and help out with your up-coming projects? :smiley:

**Comment by HyGlobalHD** [comment]
Sure.

**Comment by HyGlobalHD** [comment]
@Skull3x invited u.

**Comment by jdot-r** [comment]
What task's lay ahead of me, what can I do for you :+1:

**Comment by HyGlobalHD** [comment]
Maybe U Can Help A Bit At The Rewrite Plugin https://github.com/ArchRPG/ArchCoreSystem/tree/Rewrite

**Comment by jdot-r** [comment]
Sure

**Comment by Skull3x** [comment]
I need permissions

Everything I do does not save

**Comment by Skull3x** [comment]
And get's removed

**Comment by jdot-r** [comment]
I so did not just commit file changes in the wrong ARCHCore system repo :smile:

**Comment by jdot-r** [comment]
HyGlobalHD? Would you like to test the latest commit with me?

**Comment by HyGlobalHD** [comment]
@Skull3x sure

**Comment by Skull3x** [comment]
71.226.4.87 19132

**Comment by HyGlobalHD** [comment]
ur latest commits so interesting 👍

**Comment by jdot-r** [comment]
Thanks :smile:

**Comment by jdot-r** [comment]
The server is open

**Comment by jdot-r** [comment]
Bad part is, my new mob ai crashes you when the skeletons shoot fire balls ;-;

**Comment by HyGlobalHD** [comment]
Is That Suppose To Do That LoL xp

**Comment by jdot-r** [comment]
Lol

**Comment by jdot-r** [comment]
Yes, but I need help. Should I upload the plugin? It's an edit of PureEntities by milk

**Comment by jdot-r** [comment]
It was really trying to make bosses

**Comment by jdot-r** [comment]
Something I planned for CosmicPE

**Comment by jdot-r** [comment]
Wait

**Comment by jdot-r** [comment]
There's hyglobalhd and gamerxzavier here

**Comment by jdot-r** [comment]
Are you both the same, account wise?

**Comment by HyGlobalHD** [comment]
GamerXzavier is my ign and the github account I'm pretty sure I don't open it anymore.

**Comment by jdot-r** [comment]
Lol

**Comment by jdot-r** [comment]
I'll upload my work to my organization PocketBot

**Comment by jdot-r** [comment]
https://github.com/PocketBot-AI/PureEntities-Bosses

**Comment by HyGlobalHD** [comment]
Woah U Work So Fast lol

**Comment by HyGlobalHD** [comment]
What's Your Current Time RN? I'm 2210 Hours . Sooner Or Later I Will Go To Bed .

**Comment by jdot-r** [comment]
My current time is
 10:26 AM

**Comment by jdot-r** [comment]
![screenshot_2016-07-22-10-21-54](https://cloud.githubusercontent.com/assets/15986189/17060171/c2e1e8f8-4ff6-11e6-9b51-9d0e3136d869.png)

**Comment by jdot-r** [comment]
![screenshot_2016-07-21-13-13-53](https://cloud.githubusercontent.com/assets/15986189/17060175/c74bf4ba-4ff6-11e6-8318-1d2d0c895728.png)

**Comment by jdot-r** [comment]
Both times I crashed but got great screenshot's

**Comment by HyGlobalHD** [comment]
Its Pretty Hard To Code A Custom Mobs AI Without Crash.

**Comment by jdot-r** [comment]
Yea ;-;

**Comment by jdot-r** [comment]
![screenshot_2016-07-22-10-39-14](https://cloud.githubusercontent.com/assets/15986189/17060623/d3ef896e-4ff8-11e6-98b3-c20dad540145.png)

**Comment by Adam1609** [comment]
Suggestion:
Add damage and health base on Enchant level

**Comment by HyGlobalHD** [comment]
@Adam1609 That's Pretty Good Suggestions. But Instead Using Enchant Level Why Don't Use Level Up System Like Most MMORPG Games.

**Comment by Adam1609** [comment]
Yeah, Im ready to create the repo, and need a lot of help on that, it's just a suggestion, permantly
