### ISSUE TITLE
Background Sounds/Songs

### ISSUE THREAD

**Issue by HyGlobalHD** [BackToAction/ARCore#12]
Hey, I Just Wondering If You Know A Best Way To Make This?
Example: 
- Default Level/World (Example1 Song)
  - Others Level/World (Example2 Song)
  - ...
    I Don't Want If The Player Near NoteBlock The Songs Will Start I Want It Like When Server Start Or Player Join There Will A Song.
    Not By Command.
    Darn My Grammar :0

**Comment by Adam1609** [comment]
Sound like we have to think a song :)

**Comment by SalmonDE** [comment]
We could use like ZMusicBox nbs files. Playing the music for each player everywhere is the big deal. Perhaps we could just spawn the sounds foreach player? I think there was a NoteBlockSound class somewhere

**Comment by SalmonDE** [comment]
Yup, we would need to get the instrument and the pitch and just spawn it for every player in that specific world. Getting the instrument and pitch could be done with using nbs files and ZMusixBox's API.

https://github.com/ClearSkyTeam/ClearSky/blob/php7/src/pocketmine/level/sound/NoteblockSound.php

Look at __construct, it tells us we need a Vector3 Position, the instrument and the pitch to spawn a noteblock sound. :)

**Comment by Adam1609** [comment]
@SalmonGER you are right, but creating a server song is difficult :D maybe I should learn about note :dancer:

**Comment by SalmonDE** [comment]
It's possible to convert midi files to nbs files with NoteBlock Studio and edit the song. Maybe that could help?

**Comment by Adam1609** [comment]
See what I can do :D

**Comment by HyGlobalHD** [comment]
Working On This Stuff
