### ISSUE TITLE
Next Update on 0.0.4

### ISSUE THREAD

**Issue by Adam1609** [BackToAction/ARCore#14]
- [ ] Custom Skills (for example Blindness, LifeSteal, .....)
- [ ] Improvement for AntiLagg (delay)
- [ ] Background noteblock song 
- [x] New Pets
- [ ] Pets can follow players when changing world

**Comment by Adam1609** [comment]
@Skull3x please check this, you must create price shop for all your configuration

**Comment by HyGlobalHD** [comment]
Done With Pets
Working On With NBS Background Song
And Enchantments

**Comment by HyGlobalHD** [comment]
//closed
