### ISSUE TITLE
My server can't load database!!

### ISSUE THREAD

**Issue by lightda104530** [BackToAction/ARCore#17]
My server can't load database file message like down

[Server thread/CRITICAL]: Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/phar_OAO-master (5)_9wbhm3VseC9EnfS.phar/src/ARCore/ARCore" at line 239

Can you help me?

**Comment by Adam1609** [comment]
@HyGlobalHD hmmm.......

**Comment by HyGlobalHD** [comment]
i will check it later :-:

**Comment by lightda104530** [comment]
Thx～

**Comment by lightda104530** [comment]
Add one more thing... =< 7 need to change to <7 or it will error

**Comment by HyGlobalHD** [comment]
//closed
