### ISSUE TITLE
PlayerJoinEvent Message

### ISSUE THREAD

**Issue by MalakasPlayzMC** [BackToAction/ARCore#26]
It is not an issue. It's a request. Can you add that on the join event?

$player = $event->getPlayer();
$name = $player->getName();
$text[0] = TextFormat::DARK_PURPLE . "##########################";
$text[1] = TextFormat::AQUA . "Welcome, $name";
$text[2] = TextFormat::LIGHT_PURPLE . "Website: " . TextFormat::WHITE . "Customizable via config";
$text[3] = TextFormat::LIGHT_PURPLE . "Vote Website " . TextFormat::WHITE . "Customizable via config";
$text[4] = TextFormat::AQUA . "To Login do /login <password>. To Register do /register <password> <confirm password>";
$text[5] = TextFormat::DARK_PURPLE . "##########################";
$player->sendMessage($text[0]);
$player->sendMessage($text[1]);
$player->sendMessage($text[2]);
$player->sendMessage($text[3]);
$player->sendMessage($text[4]);
$player->sendMessage($text[5]);

**Comment by HyGlobalHD** [comment]
does the /login and /register is needed? cause there already xBox Auth

**Comment by HyGlobalHD** [comment]
I can add this but the plugin is in re-write progress, so it might be none usable for a while.

**Comment by MalakasPlayzMC** [comment]
The plugin is not for API 3.0.0 (according to readme.md). X-Box Auth is required on MCPE 1.2 and higher if I am not false.

**Comment by HyGlobalHD** [comment]
Well This Plugin Is OUTDATED, And In Re-Write Branch , I Currently Fixing Some Stuff But I Tried To Update It To The Latest API . Also I'll Tried To Update It For MCPE 1.2 And Higher, Which The Auth Is Not Needed; 
However, If You Really Need The Auth You Can Request It. 
Also Yes, According To README.md The Plugin Is Not For API 3.0.0 Or Higher Cause It's Still OUTDATED.

**Comment by NeuroBinds** [comment]
Wubb @HyGlobalHD i'm bck. And i alrdy send you a msg ahout a new project and i suggest you to drop this plug cause it a mess. But you stil can update it .

@MalakasPlayzMC  this request is wil only be implement for a msg onplayerjoin.

**Comment by MalakasPlayzMC** [comment]
I do not need the auth. Forget the $text[4]. What about the other messages?

**Comment by NeuroBinds** [comment]
Sure.

**Comment by NeuroBinds** [comment]
Anywhere, is this request to add for the rewrite branch or in the current master?

**Comment by MalakasPlayzMC** [comment]
Rewrite, the master is discontinued

**Comment by MalakasPlayzMC** [comment]
Bump

**Comment by MalakasPlayzMC** [comment]
Bump!

**Comment by MalakasPlayzMC** [comment]
Bump!

**Comment by Cynoser** [comment]
@MalakasPlayzMC https://github.com/BackToAction/ARCore/pull/29

**Comment by AcNEO** [comment]
#### please take note that this plugin wouldn't be update to frequently as stated in README.md
View https://github.com/BackToAction/ARCore/blob/master/README.md#note

**Comment by AcNEO** [comment]
close the issues, cause we're not sure to update it anymore.
I will reconsidered to add this if I had time, cause we're all very busy with RL....
sorry for the inconvenience.
