### ISSUE TITLE
Chating of WhatEver.

### ISSUE THREAD

**Issue by HyGlobalHD** [BackToAction/ARCore#5]

**Comment by HyGlobalHD** [comment]
I Change The Name To ARCore because ArchCoreSystem Name seems spamming xP

**Comment by Adam1609** [comment]
I think we should add Level System in RPG server, even in your plugin!

**Comment by HyGlobalHD** [comment]
Well Of course every RPG server need level System. I'm currently finding a best method to do so..(still didn't find any solution if u want to help feel free to..)

**Comment by Adam1609** [comment]
I think level system should base on XPOrb like in PC server!

**Comment by Adam1609** [comment]
I have an idea, what about random experience recieved in killing entity? For example:
You have kill {entity}, recieve {number} experience!
I learn from SAO server, it could work!

**Comment by NeuroBinds** [comment]
You mean an entity when you kill there some xpORB spawn at where the entity died.
or
Player  kill an entity and there a message send to the player "You gain $EXP<amount of EXP> for killing <Entity Name>.

SO, the experience were show at the xp bar or the experience shows when player do /stats
the xp bar will shows as the player level or it will shows as MP(mana points/Monster Points)

**Comment by HyGlobalHD** [comment]
hmm.. which better?

**Comment by Adam1609** [comment]
Oh yeah, it could make sense, but I think that, You gain $exp for killing should be better, because we have to calculate the experience!

**Comment by HyGlobalHD** [comment]
So the $exp should be random?
ex. 
$player - Kill - Entity 
send message ("You're Gain". $exp."for killing".$entitytype.);
$exp rand(1,2,...,1000);
$entitytype get entity name

maybe
likethat..

or
....

**Comment by HyGlobalHD** [comment]
$exp = $this->getPlayer();
$rand = rand(1,bla,bla,100);
if(blablabla kill entity){
$xp = $exp->addExp()+$rand;  NOTE: idk if this have I merely check the Player.php I just found getExp and other something..

something like that for exp add

for the level idk.. maybe I check later

**Comment by Adam1609** [comment]
If base on xporb, it could be buggy for the plugin, so it is easy to do like SAO things!

**Comment by HyGlobalHD** [comment]
Like SendTip?
But my method doesn't spawn The ExpOrb so it won't make server laggy.
My method is send the xp to the player expbar.
but I think I won't nice cause the level shows on expbar doesn't seems fancy :P

**Comment by NeuroBinds** [comment]
Can someone reviews this?
https://github.com/NeuroBinds/Simple-Guilds-Management

**Comment by HyGlobalHD** [comment]
@NeuroBinds nice but need improvement..

so how which method we should use?

I have a new ideas xP
like u say its will be great if there like SAO.
How about a custom Boss in specific place or quest
when player kill the boss or complete the quest
a floatingtextparticle will spawn in front of the player like 2 block away and shows a message like u gain item,exp,etc
then it will dispawn when player move from the particle about 5 block or more then 10/20secondond

of course it may  a little laggy or buggy but itokay to try xP

**Comment by NeuroBinds** [comment]
@Adam1609 i have a request could you reorganize the source code? like A Folder .Ex= ARCore/Enchantment/[file] and some other things..my internet kinda slow to make this

@HyGlobalHD Thanks .. i might need your help but i think i manage myself.. :P 

actually that a nice ideas but how about a normal monster?
i suggest sendTip cause if there a lot of monster then the FloatingTextParticle will be a bothering to player and may cause quiet lagg xP

**Comment by Adam1609** [comment]
@NeuroBinds okay! I will do that!

**Comment by Adam1609** [comment]
Do you think we should add gitter for easy conversation?

**Comment by HyGlobalHD** [comment]
hmm .. I never tried to use gitter before..

**Comment by Adam1609** [comment]
maybe you should try :)

**Comment by HyGlobalHD** [comment]
A reference for LevelSystem at [Here](https://github.com/famima65536/LevelSystem)

**Comment by Adam1609** [comment]
Okay I just finished the clans system, could you check?

**Comment by HyGlobalHD** [comment]
Okey.. do u want me to check the code or try it? xP

**Comment by Adam1609** [comment]
check it, I took this code 1 month ago and I think it could be useful!

**Comment by HyGlobalHD** [comment]
@Adam1609 you should check neurobinds @NeuroBinds code too might give u a nice implement..
https://github.com/NeuroBinds/Simple-Guilds-Management
check it out

**Comment by Adam1609** [comment]
But it has power management dah!

**Comment by HyGlobalHD** [comment]
lol doesn't clan also have power? like clan power when a player kill they gain clan power xP

**Comment by Adam1609** [comment]
Yes, that's the point @@ maybe we should make gitter!

**Comment by HyGlobalHD** [comment]
u should add gutter idk how :p
between I find a fix for your clans so please review it :0

**Comment by Adam1609** [comment]
okay

**Comment by Adam1609** [comment]
Next Error: Monster Spawner Leashes!

**Comment by NeuroBinds** [comment]
What Do You Mean By That? @Adam1609

**Comment by HyGlobalHD** [comment]
Skills implement delay.
My Wifi Data Connection Is Already Limited.
LoL..
I not going to contribute much i have competition...
i have exam

**Comment by HyGlobalHD** [comment]
@Adam1609 see this https://gist.github.com/HyGlobalHD/424720f0b468645e2997fea6d6a80d86

**Comment by Adam1609** [comment]
OMG, this is confusing :(

**Comment by HyGlobalHD** [comment]
You Need Imagination xP

**Comment by Adam1609** [comment]
By the way, do you need a server?

**Comment by HyGlobalHD** [comment]
I Don't Know.. LoL

**Comment by Adam1609** [comment]
I can create the server with port 19133, to test the plugin!

**Comment by SalmonDE** [comment]
I could maybe do the auto updater, but I would also need to upload a file to a website. Perhaps we could use github pages?

**Comment by HyGlobalHD** [comment]
I Need Someone To ReCALCULATE ANTIHACKS

ALSO THE PARTICLES

**Comment by daniktheboss** [comment]
$min = 1;
$max = 1000;
echo mt_rand($min, $max);

**Comment by HyGlobalHD** [comment]
//close old thread
